WebApplication1/WebApplication1/Controllers/CreateTestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using WebApplication1.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{

    /// <summary>
    /// Класс отвечает за создание новых тестов
    /// </summary>
    [Authorize(Roles = "admin")]
    public class CreateTestController : Controller
    {
        static CreateTest? _test;
        Question _question;
        static int count = 0;
        static int maxSum = 0; //максимальная сумма баллов

        UserContext _context;

        /// <summary>
        /// Конструктор
        /// </summary>
        /// <param name="context"></param>
        public CreateTestController(UserContext context)
        {
            _context = context;
        }


        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        //создание нового теста
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNewTest(CreateTest test)
        {
            if (ModelState.IsValid)//если поля введены правильно
            {
                _test = test;
                count = 1;
                maxSum = 0;

                ViewBag.QuestionCount = count;
                ViewBag.NumberChoiceInQuestio = _test.NumberChoiceInQuestion;

                return View("CreateNewQuestion");
            }
            else
            {
                return View("Index", test);
            }
        }

        //Создание нового вопроса

        [HttpPost]
        public ActionResult CreateNewQuestion(Question question)
        {
            question.Test = _test;
            question.Number = count;

            if (ModelState.IsValid) //если поля введены правильно
            {
                _test.Questions.Add(question);

                //находим максимальный бал среди баллов всех ответов этого вопроса
                int max = 0;
                for (int i = 0; i < question.Answers?.Count; i++)
                {
                    if (max < question.Answers[i].PointsNumber) max = question.Answers[i].PointsNumber;
                }
                maxSum += max;

                count++;
                ViewBag.QuestionCount = count;
                ViewBag.NumberChoiceInQuestio = _test?.NumberChoiceInQuestion;

                if (count <= _test?.NumberQuestions)
                {
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    _test.MaxSum = maxSum;
                    _context.CreateTests.Add(_test);
                    _context.SaveChanges();

                    return View("QuestionEnd");
                }
            }
            else
            {
                return View(question);
            }
        }


        //список пройденных опросов
        List<TestExecution>? TestExecutions { get; set; }

        //удалить пройденный тест
        [HttpGet]
        public ActionResult DelExecution()
        {
            LoadExecutionDateFromDb();
            return View(TestExecutions);
        }

        //Загузка данных из БД
        void LoadExecutionDateFromDb()
        {
            _context.Answers.Load();
            _context.Questions.Load();
            _context.CreateTests.Load();
            _context.Roles.Load();
            _context.Users.Load();

            TestExecutions = _context.TestExecutions.ToList();
        }


        [HttpPost]
        public ActionResult DelExecution(string[] selectedId)
        {

            foreach (var item in selectedId) //перебираем полученные строки
            {

                if (int.TryParse(item, out var id)) //преобразуем строку в число
                {
                    //ищем запись в БД
                    var record = _context.TestExecutions.FirstOrDefault(x => x.Id == id);
                    
                    if (record != null) //если запись найдена
                    {
                        //удаляем её
                        _context.TestExecutions.Remove(record);
                        _context.SaveChanges();
                    }
                }
            }

            LoadExecutionDateFromDb();
            return View(TestExecutions);
        }




        //---- создание новой группы
        [HttpGet]
        public ActionResult CreateNewGroup()
        {
            _context.Groups.Load();

            ViewBag.GroupList = _context.Groups.ToList();
            return View();
        }

        //создание новой группы
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNewGroup(Group group)
        {
            if (ModelState.IsValid)//если поля введены правильно
            {
                _context.Groups.Load();
                var list = _context.Groups.ToList();

                if (list.Find(x => x.Name.ToUpper() == group.Name.ToUpper()) == null)  //если группы с таким названием нет
                { //добавляем группу в в БД
                    _context.Groups.Add(group);
                    _context.SaveChanges();

                    list = _context.Groups.ToList();
                    ViewBag.Rezul = "Группа добавлена в БД";
                }
                else
                {
                    ViewBag.Rezul = "Группа с таким названием уже есть в БД";
                }

                return View("GroupAddRezult", list);
            }
            else
            {
                return View();
            }
        }


        //---- Информация по зарегистророванным пользователям
        [HttpGet]
        public ActionResult ShowUserInfo()
        {
           
            _context.Groups.Load();
            _context.Users.Load();

            ViewBag.UsersList = _context.Users.ToList();
            return View();
        }

    }
}

WebApplication1/WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using WebApplication1.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{

    //Главный контроллер
    [Authorize]
    public class HomeController : Controller
    {
        UserContext _context;
        public HomeController(UserContext context)
        {
            _context = context;
        }


        [AllowAnonymous]
        public IActionResult Index()
        {
            int hour = DateTime.Now.Hour; //время сейчас
            string greeting;

            switch (hour)
            {
                case < 6:
                    greeting = "Доброй ночи";
                    break;
                case >= 6 and < 12:
                    greeting = "Доброй УТРО";
                    break;
                case >= 12 and < 18:
                    greeting = "Доброй день";
                    break;
                case >= 18 and < 24:
                    greeting = "Доброй вечер";
                    break;
                default:
                    greeting = "";
                    break;
            }

            ViewBag.Greeting = greeting;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [AllowAnonymous]
        public ViewResult ShowTestsList()
        {
            AboutTest aboutTest = new AboutTest(_context);
            aboutTest.SetDataToList();
            return View(aboutTest);
        }


        [AllowAnonymous]
        public ViewResult ShowGroupStattistic()
        {
            GroupsStatistic groupStatistic = new GroupsStatistic(_context);
            groupStatistic.SetDataToList();
            return View(groupStatistic);
        }
    }
}

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Анкетирование студентов";
}


<h2 align="center">@ViewBag.Greeting!</h2>
<h3 align="center">Поздравляем! Вы пришли на сайт анкетирования!</h3>

<ul>
    <li>
        <div>
            Ресурсы доступные для всех:
            <br />
            <a asp-action="ShowTestsList">Результаты опросов</a>
            <br />
            <a asp-action="ShowGroupStattistic">Статистика по группам</a>
        </div>
    </li>
    
    <li>
        <div>
            Ресур доступен только для авторизованных пользователей:
            <br />
            <a asp-controller="RunTest">Пройти опрос</a>
        </div>
    </li>

    <li>
        <div>
            Ресурсы доступеные только администратору:
            <br />
            <a asp-controller="CreateTest">Создание нового опроса</a>
            <br />
            <a asp-controller="CreateTest" asp-action="DelExecution">Удалить опросы</a>
            <br />
            <a asp-controller="CreateTest" asp-action="CreateNewGroup">Ввод новой группы</a>
            <br />
            <a asp-controller="CreateTest" asp-action="ShowUserInfo">Информация по зарегистрированным пользователям</a>
        </div>
    </li>
    
</ul>

WebApplication1/WebApplication1/Views/Home/ShowGroupStattistic.cshtml
@model WebApplication1.ViewModels.GroupsStatistic
@{
    ViewData["Title"] = "Статистика по группам";
}



<h3 align="center">Список доступных тестов</h3>
<table>
    <caption style="background:Khaki">Информация по всем доступным опросам</caption>

    <thead>
        <tr>
            <th>Название опроса</th>
            <th>Описание</th>
            <th>Количество вопросов</th>
            <th>Максимально баллов</th>
            <th>Группа</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.CreateTests)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.NumberQuestions</td>
                <td>@item.MaxSum</td>
                <td>

                    <table>
                        <thead>
                            <tr>
                        <th>Название</th>
                        <th>Кол. раз пройден</th>
                        <th>Сумма баллов</th>
                        <th>Средний балл</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach (var group in Model.Groups)
                            {
                                
                                    int count = Model.TestExecutions.Count(x => x.CreateTest.Id == item.Id
                                            && x.User.Group.Id == group.Id);

                                    int? sum = Model.TestExecutions.Where(x => x.CreateTest.Id == item.Id
                                            && x.User.Group.Id == group.Id).Sum(z => z.AnswersSum);

                                decimal? avg = null;
                                if (sum!=null &&  count!=0)
                                {
                                    avg = (decimal)sum / count;
                                }


                                <tr>
                                    <td>@group.Name</td>
                                    <td>
                                        @count
                                        @*@Model.TestExecutions.Count(x=>x.CreateTest.Id==item.Id
                                            && x.User.Group.Id==group.Id)*@
                                    </td>
                                    <td>
                                        @sum
                                        @*@Model.TestExecutions.Where(x=>x.CreateTest.Id==item.Id
                                            && x.User.Group.Id==group.Id).Sum(z=>z.AnswersSum)*@
                                    </td>
                                    <td>
                                        @avg
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </td>
            </tr>
        }

    </tbody>
    <tfoot>
        <tr>
            <th>Итого опросов:</th>
            <th>@Model.CreateTests.Count</th>
        </tr>
    </tfoot>
</table>

WebApplication1/WebApplication1/Views/Home/ShowTestsList.cshtml
@model WebApplication1.ViewModels.AboutTest
@{
    ViewData["Title"] = "Анкетирование студентов";
}

<h3 align="center">Список доступных тестов</h3>
<table>
    <caption style="background:Khaki">Информация по всем доступным опросам</caption>

    <thead>
        <tr>
            <th>Название опроса</th>
            <th>Описание</th>
            <th>Количество вопросов</th>
            <th>Максимально баллов</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.CreateTests)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.NumberQuestions</td>
                <td>@item.MaxSum</td>
            </tr>
        }

    </tbody>
    <tfoot>
        <tr>
            <th>Итого опросов:</th>
            <th>@Model.CreateTests.Count</th>
        </tr>
    </tfoot>
</table>

@*-------------------------  вторая таблица ---------------------------*@
<br />
<h3 align="center">Результаты прохождения тестов</h3>
<table>
    <caption style="background:Khaki">Информация по всем пройденным тестам</caption>

    <thead>
        <tr>
            <th>Пользователь</th>
            <th>Группа</th>
            <th>Название опроса</th>
            <th>Количество баллов</th>
            <th>% набранных баллов </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.TestExecutions)
        {
            <tr>
                <td>@item.User.Name</td>
                <td>@item.User?.Group?.Name</td>
                <td>@item.CreateTest.Name</td>
                <td>@item.AnswersSum</td>
                <td>@(100*item.AnswersSum/item.CreateTest.MaxSum)</td>
            </tr>
        }

    </tbody>
    <tfoot>
        <tr>
            <th>Итого пройденных тестов:</th>
            <th>@Model.TestExecutions.Count</th>
        </tr>
    </tfoot>
</table>

@*-------------------------  третья таблица ---------------------------*@

<br />
<h3 align="center">Статистика</h3>
<table>
    <caption style="background:Khaki">Статистика набранных % по тестам</caption>

    <thead>
        <tr>
            <th>Тест</th>
            <th>Кол. тестов, в которых набрано [0;30]% баллов</th>
            <th>Кол. тестов, в которых набрано [31;60]% баллов</th>
            <th>Кол. тестов, в которых набрано [61;100]% баллов</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.StatInfo)
        {
            <tr>
                <td>@item.Test.Name</td>
                <td>@item.To30</td>
                <td>@item.To60</td>
                <td>@item.To100</td>
            </tr>
        }

    </tbody>
</table>